### ISSUE TITLE
『이건우의 퍼블리싱』에 대한 "(구)파트장 시점" 고찰

### ISSUE THREAD

**Issue by smlee98** [gwlee-dev/gridone-corp#1]
![image](https://user-images.githubusercontent.com/69204232/147337204-8a11307a-9811-48ea-a89d-b5f11e00fee0.png)
- [x] 푸터만 손좀 봐줘유

**"크흣··· 이것이 (현)파트장의 『실력』인가···"**

**Comment by gwlee-dev** [comment]
ㅋㅋ

**Comment by smlee98** [comment]
![images](https://user-images.githubusercontent.com/69204232/147338417-c86b2358-a8bf-4335-8fc1-b833c3638458.jpg)
@gwlee-dev

**Comment by smlee98** [comment]
![download](https://user-images.githubusercontent.com/69204232/147338440-f129ff9c-a8b5-419b-98c8-f0fccd0ba245.jpg)
@smlee98

**Comment by gwlee-dev** [comment]
![KakaoTalk_20211116_180115011](https://user-images.githubusercontent.com/81747455/147338493-c80e171a-8205-4b4a-b2bd-0ca252326a2a.png)
ㅎㅇ

**Comment by smlee98** [comment]
![images](https://user-images.githubusercontent.com/69204232/147338557-a17f6554-59b2-4834-ac88-d02f2bbab7e1.jpg)
